# Generated by Django 4.2.11 on 2024-04-12 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutortialapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200, null=True)),
                ('lastname', models.CharField(max_length=200, null=True)),
                ('subject', models.CharField(choices=[('ELA', 'ELA'), ('Social Studies', 'Social Studies'), ('Math', 'Math'), ('Science', 'Science'), ('Foreign Language', 'Foreign Language'), ('Business', 'Business'), ('PE', 'PE')], max_length=200, null=True)),
                ('roomnum', models.IntegerField()),
            ],
        ),
    ]
