# Generated by Django 4.2.11 on 2024-05-06 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tutortialapp', '0002_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='firstname',
            field=models.CharField(max_length=200, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.CharField(choices=[('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], max_length=200, null=True, verbose_name='Grade'),
        ),
        migrations.AlterField(
            model_name='student',
            name='lastname',
            field=models.CharField(max_length=200, null=True, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='middlename',
            field=models.CharField(max_length=200, null=True, verbose_name='Middle Name(s)'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='firstname',
            field=models.CharField(max_length=200, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='lastname',
            field=models.CharField(max_length=200, null=True, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='roomnum',
            field=models.IntegerField(verbose_name='Room Number'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subject',
            field=models.CharField(choices=[('ELA', 'ELA'), ('Social Studies', 'Social Studies'), ('Math', 'Math'), ('Science', 'Science'), ('Foreign Language', 'Foreign Language'), ('Business', 'Business'), ('PE', 'PE')], max_length=200, null=True, verbose_name='Subject'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200, null=True, verbose_name='First Name')),
                ('lastname', models.CharField(max_length=200, null=True, verbose_name='Last Name')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
