# Generated by Django 5.0.4 on 2024-05-13 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutortialapp', '0003_alter_student_firstname_alter_student_grade_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='lastname',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='middlename',
            new_name='middle_name',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='lastname',
            new_name='last_name',
        ),
    ]
