# Generated by Django 4.2.11 on 2024-05-13 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutortialapp', '0004_rename_firstname_student_first_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
